#!/usr/bin/env bash
# For brightness notifications

msgTag="brightness-change"
max_brightness=$(cat /sys/class/backlight/*/max_brightness)
current_brightness=$(cat /sys/class/backlight/*/brightness)
percentage=$(((100 * current_brightness + max_brightness / 2) / max_brightness)) # Rounded percentage
icon="preferences-system-brightness-lock"

dunstify -a "changeBrightness" -u low -i "$icon" -h string:x-dunst-stack-tag:"$msgTag" \
  -h int:value:"$percentage" "Brightness: $percentage%"
